
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  datasource:
      url: jdbc:oracle:thin:@localhost:1521:xe
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: twitter
      password: twitter

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties: 
      '[hibernate.format_sql]': true 

  output: 
    ansi:
      enabled: always
